### ISSUE TITLE
panic:  stat : no such file or directory

### ISSUE THREAD

**Issue by gregwebs** [marmelab/gaudi#30]
.gaudi.yml

```
applications:
  mongodb:
    type: remote
    image: dockerfile/mongodb
    ports:
      27017: 27017
      27018: 27018
```
