### ISSUE TITLE
When using nginx, the php app doesn't seems to be linked correctly

### ISSUE THREAD

**Issue by pengux** [marmelab/gaudi#36]
Accessing a PHP script gives 403 Forbidden. Here is a sample configuration:

``` yaml
applications:
    front1:
        type: nginx
        links: [app]
        ports:
            80: 80
        volumes:
            .: /var/www
        custom:
            fastCgi: app

    app:
        type: php-fpm
        links: [db]
        ports:
            9000: 9000
        volumes:
            .: /var/www

    db:
        type: mysql
        ports:
            3306: 3306
```
