### ISSUE TITLE
Error at step 7 with Symfony application

### ISSUE THREAD

**Issue by blazarecki** [marmelab/gaudi#41]
Hi, 

First of all, I would like to thanks you for this awesome tool, that makes docker fun and easy to use!

I have an issue with this configuration 

`.gaudi.yml`

``` yml
applications:
    front:
        type: apache
        links: [app]
        ports:
            80: 80
        volumes:
            .: /var/www
        custom:
            fastCgi: app
            documentRoot: /var/www/web
            modules: [rewrite]

    app:
        type: php-fpm
        links: [db]
        ports:
            9000: 9000
        volumes:
            .: /var/www

    db:
        type: mysql
        ports:
            3306: 3306
        after_script: mysql -e "CREATE DATABASE symfony CHARACTER SET utf8 COLLATE utf8_general_ci;" -uroot
        volumes:
            .gaudi/mysql: /var/lib/mysql
```

The issue is:

```
Step 7 : RUN grep -v rootfs /proc/mounts > /etc/mtab
 ---> Running in da791898e3a0
grep: write error
2014/04/24 22:25:48 The command [/bin/sh -c grep -v rootfs /proc/mounts > /etc/mtab] returned a non-zero code: 2
```

[Here the full log detail](http://pastebin.com/bRkkeHYh)

The command `docker images` give me this:

```
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
gaudi/app           latest              8aac370342de        21 minutes ago      426.6 MB
<none>              <none>              02fd943f962b        22 minutes ago      528.4 MB
<none>              <none>              20ca3d4c2914        22 minutes ago      398.7 MB
stackbrew/debian    wheezy              5128521927a1        4 hours ago         115 MB
```

Any idea ? 

Thanks!
