### ISSUE TITLE
mysql template

### ISSUE THREAD

**Issue by amenophis** [marmelab/gaudi#78]
Hi,
It seems the mysql template does not let the container in running state after building.
Can you take a look ?

.gaudi.yml

```
db:
    type: mysql
    ports:
        3306: 3306
    after_script: mysql -e "CREATE DATABASE mydb CHARACTER SET utf8 COLLATE utf8_general_ci;" -uroot
    volumes:
        .gaudi/mysql: /var/lib/mysql
```

Thanks
